version: 2.1
orbs:
  hugo: circleci/hugo@1.3.0

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - hugo/build:
          html-proofer: true
      - store_test_results:
          path: test_results

workflows:
  main-workflow:
    jobs:
      - build-and-test